### ISSUE TITLE
如果用英语的或者其他语言

### ISSUE THREAD

**Issue by bourne-3** [liweimin1996/Min_NLP_Practice#5]
如果用英语的或者其他语言，这个模型需要修改哪里呢

**Comment by liweimin1996** [comment]
版本问题应该很容易解决，如果想使用英语或者其他语言可以修改 https://github.com/liweimin1996/Min_NLP_Practice/tree/master/model
里面的词向量，这里使用的是中文词向量，修改为GitHub上开源的其他语言词向量即可。
不过现在推荐用bert类的模型处理这个问题
